image: docker:19.03.5

stages:
  - build
variables:
  DOCKER_DEV_URL: registry.gitlab.com/riddhid1/laravel-1-project/build-laravel
services:
  - 'docker:19.03.5-dind'
build-laravel:
  stage: build
  script:
    - 'docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY'
    - 'apk add --no-cache curl jq python py-pip'
    - 'docker build --pull -t $DOCKER_DEV_URL:$CI_JOB_ID -f main.Dockerfile .'
    - 'docker push $DOCKER_DEV_URL:$CI_JOB_ID'
  only:
    - main